"""
ChatbotController.py - AI chatbot routes

Hosts endpoints for the chatbot interaction, relaying prompts/responses via the configured LLM provider.
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List
import google.generativeai as genai


router = APIRouter()

gemini_api_key: str | None = None


def init_chatbot_controller(api_key: str | None):
    global gemini_api_key
    gemini_api_key = api_key
    if gemini_api_key:
        genai.configure(api_key=gemini_api_key)


class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    messages: List[ChatMessage]


@router.post("/api/chat")
async def chat(chat_request: ChatRequest):
    try:
        if not gemini_api_key:
            raise HTTPException(
                status_code=HTTPException.status_code if isinstance(HTTPException, type) else 503,
                detail="Chatbot is currently disabled. Please contact support.",
            )

        model = genai.GenerativeModel("gemini-2.5-flash")

        if not chat_request.messages:
            raise HTTPException(
                status_code=400,
                detail="No messages provided. Please include at least one user message.",
            )

        contents = [
            {"role": msg.role, "parts": [{"text": msg.content}]}
            for msg in chat_request.messages
        ]

        response = await model.generate_content_async(contents)

        if not response or not response.candidates:
            raise HTTPException(
                status_code=502,
                detail="No response generated by the AI model.",
            )

        candidate = response.candidates[0]
        if not candidate.content or not candidate.content.parts:
            raise HTTPException(
                status_code=502,
                detail="Empty response from the AI model.",
            )

        text_parts = [
            part.text
            for part in candidate.content.parts
            if hasattr(part, "text") and part.text
        ]
        answer = "\n".join(text_parts).strip() or "I couldn't generate a response. Please try again."

        return {"message": answer}

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error processing chat request: {str(e)}",
        )
